### ISSUE TITLE
Add lovelace config options

### ISSUE THREAD

**Issue by maykar** [maykar/kiosk-mode#22]
Add in config options to be set in lovelace. This will help solve some issues related to the fact that the companion apps are unable to use query strings and be helpful in general.

**Comment by skank01** [comment]
follow mode

**Comment by maykar** [comment]
follow mode?

**Comment by maykar** [comment]
Follow mode? If that was just a comment so that you get notifications on this issue, that is what the subscribe button on the right of this page is for. Please, don't comment just for the sake of commenting.

![image](https://user-images.githubusercontent.com/25127328/98170829-b6884180-1ebc-11eb-8de7-adf606720a11.png)

**Comment by KTibow** [comment]
you can hide comments @maykar

**Comment by maykar** [comment]
I know and I will, but it's a bad habit to get into. Not only does it clutter up issues and PRs, it forces action on the part of the maintainers. Just doing my part to inform that not only is it poor form, it's easier to just click that subscribe button.

All these comments will be hidden or deleted in time 😃.

**Comment by maykar** [comment]
Added in latest release:

https://github.com/maykar/kiosk-mode#configuration-in-lovelace
