### ISSUE TITLE
Stable only when Debugger is open

### ISSUE THREAD

**Issue by benji1703** [maykar/kiosk-mode#23]
Hi Guys!

First, thank you very much for your contribution. 

I'm failing to use this since this won't work stable at all. Looks like, for some reason, the MutationObserver are not waiting for rendering.

Weird enough, this work flawlessly when Debugger is opened.

Tested an replicated on FF and Chrome.

**Comment by maykar** [comment]
Working with dev-tools open suggests a cache issue.

* How did you install, HACS or Manually?
* What options are you trying to use and how are you using them?
* If you're installing manually are you grabbing the file from the releases page and increasing the version number in your resources?

**Comment by maykar** [comment]
Also, if you keep your dev-tools closed and it fails to work and then you open your dev-tools console are there any errors pertaining to kiosk-mode?

**Comment by benji1703** [comment]
Again - thank you for the response.

1. Installation from HACS - using latest.
2. Using '?kiosk' (e.g. http://*local*:8123/lovelace/0?kiosk)
3. Happening on other devices as well.
4. Clean cache - fix the issue for One refresh only.

Before - Clean Cache:
![Screen Shot 2020-11-05 at 20 03 39](https://user-images.githubusercontent.com/28018078/98279045-1c9ac480-1fa2-11eb-8825-a944ce4901f6.png)

 Clean Cache:
![Screen Shot 2020-11-05 at 20 04 56](https://user-images.githubusercontent.com/28018078/98279271-57046180-1fa2-11eb-9cbc-5db5768f53d2.png)

Reload:
![Screen Shot 2020-11-05 at 20 06 23](https://user-images.githubusercontent.com/28018078/98279349-756a5d00-1fa2-11eb-922b-8a174794d8bd.png)

**Comment by KTibow** [comment]
Does the same issue occur if you delete the gz file in `/config/local/community/kiosk-mode` and then replace the non-gz file with the uncompressed version [here](https://raw.githubusercontent.com/maykar/kiosk-mode/master/kiosk-mode.js)?

**Comment by benji1703** [comment]
I've tried and getting 

Uncaught TypeError: Cannot read property 'config' of undefined
    at getConfig (kiosk-mode.js:8)
    at kiosk_mode (kiosk-mode.js:48)
    at kiosk-mode.js:88

main.querySelector("ha-panel-lovelace") is undefined :(

**Comment by KTibow** [comment]
Do you use v0.117?

**Comment by benji1703** [comment]
Yes, using 0.117.0

**Comment by maykar** [comment]
Seems like a strange race condition. Not only are you having issues with hui-root not existing when it should, but even stranger is the face that the lovelace panel wouldn't exist after this resource is loaded. You doing some pretty heavy customization?

As much as I hate timeouts, I added some to my latest commit. See if it helps, replace the js file like you did before with the one I just added commits to: https://raw.githubusercontent.com/maykar/kiosk-mode/master/kiosk-mode.js

**Comment by maykar** [comment]
On lines 85 and 114 are the two millisecond values for the timeouts. The one on 85 is for kiosk mode's run and the one on 114 is for the observer that waits to run when hui-root appears.

If you're still having issues after trying with the values that are there you can try increasing them to see if it helps.

**Comment by benji1703** [comment]
Yes, using quite heavy UI extension, and running on a poor RPi3.
Will use some timeout for the kiosk_mode().

When I first read the code I was sure that you guys are monitoring using MutationObserver... Will try to optimize this later on this night. Thanks.

**Comment by maykar** [comment]
On first run there's really no need for a mutation observer as all those elements "should" exist before this is even loaded.  After that I add mutation observers to watch for dashboard changes as the script needs to rerun when you navigate to a new dashboard.

**Comment by maykar** [comment]
Your system seems to even have trouble with the mutation observer as well, though. As before I added the timeouts the observer watches for hui-root to appear and watches for elements to appear in it's shadowRoot, but on your system the element's shadowRoot doesn't appear in time for that observer to be added.

Again, strange race condition.

**Comment by benji1703** [comment]
Yep, the timeout is not good enough, will need to find a good explanation.
Will close this, as this is probably related to my HASS.
