### ISSUE TITLE
Stops working when refreshing page

### ISSUE THREAD

**Issue by ASNNetworks** [maykar/kiosk-mode#27]
As of today kiosk-mode started to act very strange. I hit reload (ctrl+r) when I was working on my UI in YAML (like I'v been doing for the past months) and suddenly the sidebar and header were back. I use applicationize.me. So thought, I'll delete the extension and create a new one perhaps something is just bugged. 

The new one worked, but as soon as I hit reload it showed the header and sidebar yet again. Now this is the stranger part: when I go through my browder (Edge chromium) and open the dashboard, it's in kiosk mode. When I hit ctrl+r to reload the page, the header and and sidebar are back again. When I change dashboards or reload, it stays that way (still visbile). BUT when I close the tab entirely and open my instance again and open the dashboard: again in kiosk mode. Reloading results in header and sidebar to return again. Closing tab again and opening the dashboard, reloads it again in kiosk mode (this I can repeat on and on).

This same behavior happens on my Samsung tablet opening this dashboard. This had worked fine untill today. I tried all the versions in HACS right now and all show the same issue suddenly. Just to clarify, I use this code in mn lovelace view YAML (dashboard)

```
kiosk_mode:
  kiosk: true
```
Before I used the `?kiosk` entry after the url for my tablet mode dashboard (was the file from a Github user which mattias later used and put on HACS). And I had the theme setting to disable the header (also for my smartphone dashboard)

```
  card-mod-root: |
    app-header {
      display: none;
    }
```
Then this option came about and tried this, and deleted the theme variable. Which worked fine up untill today. 

I also have a smartphone dashboard where I disabled the header:

```
kiosk_mode:
  hide_header: true
```

This shows the exact same behaviour, also on my iPhone. But there the header disappears after a pull to refresh. If I do it a few times, the header is sometimes back. This looks a lot (a LOT) like an infamous bug in Custom Header that always kept coming back where the header was reset.

Then I used the plugin somewhere from Github with the `?kiosk` add behind the url for my tablets. Right now I have enabled the theme line again and all works again.

I don't know what causes this, but there definitely is an issue somewhere. For now I have enabled the theme variable and have hidden the sidebar through options. This is not a big issue for me, since I disable the header on all my dashboards anyway and I don't see the sidebar now. But perhaps others experience this as well.

**Comment by maykar** [comment]
Can't replicate this one, tried on all devices and all browsers I could and after endless refreshing I have no issues. Do you get any errors in your browsers dev tools console when this happens? Seems like you can somewhat replicate it.

**Comment by maykar** [comment]
Made a few changes recently, not sure if they would be related to your issues. If you were using the cache feature before on any of the devices be sure to clear them with `?clear_km_cache`. Let me know if you notice any errors as mentioned above if this remains an issue.

**Comment by maykar** [comment]
No other reports of this issue, quite a few changes have happened since, and no additional information has been given. Marking this as stale. If this is happening to anyone else or if OP is still having this issue, please let me know and provide any errors in HA logs or dev tools console if available.
