### ISSUE TITLE
Does not work in Fully Kiosk browser

### ISSUE THREAD

**Issue by wbilger** [maykar/kiosk-mode#28]
Does not work in  Fully Kiosk browser, free or pro version.
I have cleared cache and even uninstalled, and tried on a new device as well.
Tried both enabled in .yaml and adding ?kiosk to url.

**Comment by maykar** [comment]
Working fine in fully kiosk (either version) on the multiple android devices I've tested on using latest version. What devices are you using?

**Comment by wbilger** [comment]
I have 2 LG G5 phones that it doesn't work on, both Android 8, and a HUAWEI
MediaPad T5, also Android 8.

**Comment by maykar** [comment]
How did you install, with HACS or manually? Does the resource exist in your lovelace resources and what does it look like? If viewing HA on a computer do you get any errors in the browsers dev-tools console?

This is working on all the android devices I can test, most of which pixel phones and are the most recent version of android, but this is also working on my older Fire tablet.

**Comment by wbilger** [comment]
Ok, I am away for 2 days, I will test this on Tuesday and let you know.

**Comment by KTibow** [comment]
@wbilger does it even work at all?

**Comment by wbilger** [comment]
Yes it does, it works on the same devices on chrome, and it works on chrome
on all of my PC's.

**Comment by maykar** [comment]
Try Fully Kiosk settings: Advanced Web Settings. At the very end select "Select Webview Implementation" if you have multiple options there: try some of them. If you only have one option: let us know what it is and the version number.

**Comment by wbilger** [comment]
Webview implementation - Chrome 86.0.4240.185
Chrome is the only option, system webview is disabled.

**Comment by maykar** [comment]
So, Fully Kiosk is using the same webview as chrome on at least that device, using this in chrome on that device works just fine, and that's the same webview version on my devices where Fully Kiosk is working just fine. Well that's just curious.

**Comment by maykar** [comment]
When you get the chance, try to answer the questions from the https://github.com/maykar/kiosk-mode/issues/28#issuecomment-723650755 that haven't already been answered.

**Comment by wbilger** [comment]
I installed with HACS, and just on Friday, not sure what the highest
version was then.
I just checked now, and it was on 1.35, and there was a bunch of 1.4x
updates since then, I just updated and now it works on all devices. Maybe
HACS installed an old version? Not sure, but it works great now, so you can
close this. Thanks for all of your help.

**Comment by wbilger** [comment]
I apologize as this issue should maybe not have been closed, as it still exsits, I just have not had time to look at it again until now.
What happens is it works once, then when you exit Fully Kiosk browser, the next time you open the header is not hidden.
This is still the same on the newest version, installed today.
I have 4 tablets/phones that all have this issue, all are running Android 8.
One thing that we assumed earlier that this was only not working in Fully with chrome webview and working in Chrome on same device, but that seems to not be the case, the same behaviour happens on chrome, works once (after cache cleared), then when closed and opened again, kiosk mode doesn't work (or hide_header, not sure about hide_sidebar as doesn't show on mobile).

**Comment by maykar** [comment]
Not sure what your issue is, using an Android 8 tablet and phone that I have I do not see these issues. Do you get any errors in the logs? What is your config?

**Comment by wbilger** [comment]
On all devices I have, which happen to all be Android 8, it does not work,
in Fully and on chrome.
On my PC, it does work.
My config is all yaml, and I am using split yaml files, so maybe that is
where the issue lies, but like I said, it does work on chrome on PC.
No errors in the logs.

**Comment by maykar** [comment]
I meant how are you configuring kiosk mode? Are you using the yaml config option (if so share your config) or are you just using the query strings (if so are you using the caching method, do you use the query string each time you connect)?

**Comment by wbilger** [comment]
I use yaml;
kiosk_mode:
  kiosk: true
But I have tried the caching method as well, same result.
I know it is working as it works as it works on chrome on PC's, although
sometimes the sidebar shows up and I have to refresh the page.
Just seems to be android 8, and it does work if I clear the cache, but it
only works once, next time I load the page, either browser refresh or
closing and going back in, it no longer works, and never works again until
I clear cache. This is consistent on 4 different devices I have.
One thing I have that may be different than other setups in .yaml mode is i
have split yaml, so my ui-lovelace.yaml looks like this;
title: Home Assistant
kiosk_mode:
  kiosk: true
views:
  - !include /config/lovelace/views/home.yaml
#default view Home
  -  !include /config/lovelace/views/dashboard.yaml
#Home Dashboard (Tablet) view
  - !include /config/lovelace/views/rooms/bedroom.yaml          #Rooms
... ~ 17 more includes here
resources:
  - url: /hacsfiles/kiosk-mode/kiosk-mode.js
    type: module ...

**Comment by maykar** [comment]
And your resources section is in configuration.yaml not ui-lovelace.yaml correct?

**Comment by wbilger** [comment]
Resources is in ui-lovelace.yaml.

**Comment by maykar** [comment]
That is not the correct place for resources, it should be under the `lovelace:` section of `configuration.yaml` when using YAML mode, see here:

https://www.home-assistant.io/lovelace/dashboards-and-views/#adding-more-dashboards-with-yaml

**Comment by wbilger** [comment]
I'm pretty sure they're fine in ui-lovelace.yaml, as all of my resources
work, but I tried moving resources to configuration.yaml, and same issue
still. One thing I just noticed, not sure if it will help or not, but it
works once, but not again, but I just can't clear cache, I also have to
clear data in Fully. For chrome on android it only ever works again if I
use incognito (or clear all cookies etc in chrome).

**Comment by maykar** [comment]
You for sure have some strange caching issue. Some steps to try:

* On all devices and on all browsers (fullyKiosk, chrome, etc) visit HA with the ?clear_km_cache query string and quit
* Don't reopen on those devices until after the next steps
* On a computer uninstall kiosk-mode via HACS
* Open on those devices/browsers again making sure not to use any query strings
* Clear the cache on all the devices browsers (fullyKiosk, chrome, etc)
* Reinstall kiosk-mode

**Comment by maykar** [comment]
Also, you might want to check the last comment on github as it was edited and I notice you're responding via email which won't reflect the edits made to comments.

**Comment by wbilger** [comment]
I have tried all of that before, but I believe I found the issue.
As you can see a few posts ago, I have all of my dashboard views in split
yaml in ui-lovelace.yaml.
On my second view in the list (which I didn't show in the post) I had an
extra space between the - and the !include, once I removed that extra
space, it works. So, my fault, but, not sure how it worked on PC, but not
Fully, and also everything loaded ok, but just kiosk mode that didn't work.
If debugging this I may have found another issue, not sure if I should open
another issue or continue here.
kiosk_mode:
  kiosk: true
kiosk: true works no matter what for me now, but if I try to use
entity_settings: it stops working. I tried removing some of my !includes
and it starts working again, and then I found out I could enable some, and
which ones didn't matter, but at a certain point kiosk mode stopped
working, and depending on which include I added back in, so I assume it was
the number of lines being loaded. It seems like some sort of timeout issue.
I can work around this, there are other methods to disable kiosk mode, but
not as easy, so not sure if you want to find this issue that doesn't seem
to affect many people, or maybe nobody but me.

**Comment by maykar** [comment]
I'm not sure I'm understanding the issue here, but if all you want is a way to turn kiosk mode on and off only use entity_settings and don't set anything in the main config:

```
kiosk_mode:
  entity_settings:
    - entity:
        input_boolean.kiosk_mode: 'on'
      kiosk: true
```

**Comment by wbilger** [comment]
What I am saying is, no matter what, this works;
```
kiosk_mode:
  kiosk: true
```
But, this;
```
kiosk_mode:
  entity_settings:
    - entity:
        input_boolean.kiosk_mode: 'on'
      kiosk: true
```
only works with only so many lines of lovelace yaml. I have all of my lovelace yaml in !include files, so if I enable them kiosk_mode doesn't work, but if I disable some of them, therefore eliminating a number of lines of yaml, it works. It is not a specific !include that maybe has errors in it, as all work, and multiple work, but after a certain amount are enabled, kiosk_mode stops working. This is on all devices, not just Fully.

**Comment by maykar** [comment]
If this happens on all devices do you get any errors in your logs or in your browsers dev tools console on a computer?

**Comment by wbilger** [comment]
I see no errors related to kiosk mode, but I see 3 errors due to custom cards, if I disable those custom cards in resources and it now works on chrome on PC. But, on fully only the basic kiosk mode works, the example with entity_settings doesn't (unless I remove some of my includes).
But, as I typed this, I just saw there was an update, and the new mobile_settings now works with all devices. 
Except, entity_settings doesn't override anything on any mobile devices, they all stay in kiosk mode, which is ok with me, but doesn't seem to work for me as described there.

**Comment by maykar** [comment]
false values will fallback to whatever was set before them unless specified (will try to make this more clear in the readme). So, if you want a true override including a false value you would do something like this to explicitly say true or false based on state:

```
 kiosk_mode:
  entity_settings:
    - entity:
        input_boolean.kiosk_mode: 'on'
      kiosk: true
    - entity:
        input_boolean.kiosk_mode: 'off'
      kiosk: false
```

As far as your other issues, are you still defining your resources in ui-lovelace.yaml and at the end of that file? If so, I would highly suggest defining your resources in configuration.yaml. It used to be that you defined them in ui-lovelace.yaml, but that changed a while back (though apparently still works to some extent).

Without seeing your whole config, errors for the other cards, etc, I can't really say much else. Even with all that info I cannot really offer my time to comb through it and troubleshoot what is going on.

**Comment by wbilger** [comment]
No worries, I am happy with how it is working now.
