### ISSUE TITLE
config loading failure

### ISSUE THREAD

**Issue by yinonco** [maykar/kiosk-mode#31]
most of the time it doesnt work for me.
I get an error in the console:
```
Uncaught TypeError: Cannot read property 'config' of undefined
    at m (kiosk-mode.js:17)
    at u (kiosk-mode.js:21)
    at kiosk-mode.js:35
```
which is raised from `kiosk_mode.js` line `8` `return ll && ll.lovelace.config.kiosk_mode ? ll.lovelace.config.kiosk_mode : {};`

I had a breakpoint in that line and it seems like the `ll.lovelace` object is `undefined` and only being initialized after the `kiosk_mode` loads.

When I click Ctrl+F5 it works just fine. But, when I only click F5 or when I enter the site it doesnt work

**Comment by KTibow** [comment]
Can you use the un-minified version and see if you still get the error? This might be caused by uglify.js. https://raw.githubusercontent.com/maykar/kiosk-mode/master/kiosk-mode.js

**Comment by yinonco** [comment]
still getting the same error

```
Uncaught TypeError: Cannot read property 'config' of undefined
    at getConfig (kiosk-mode.js:8)
    at kiosk_mode (kiosk-mode.js:57)
    at kiosk-mode.js:119
```

**Comment by KTibow** [comment]
Upgrade Home Assistant?

**Comment by yinonco** [comment]
I am using the latest stable version for both Home Assistant and OS

**Comment by KTibow** [comment]
Clear cache? What version of Home Assistant do you use?

**Comment by c0bra99** [comment]
I'm seeing the same error in my log. I'm running Home Assistant 0.117.5, on HassOS 4.16 (just updated from 4.15 today but not sure if this issue existing before or only after the update)

`Logger: frontend.js.latest.202010214
Source: components/system_log/__init__.py:193
First occurred: 9:08:07 PM (1 occurrences)
Last logged: 9:08:07 PM

https://dnsnamehere/hacsfiles/kiosk-mode/kiosk-mode.js:17:24 Uncaught TypeError: Cannot read property 'config' of undefined`

**Comment by yinonco** [comment]
clearing the cache didnt work for me.
And as for your question I am using:
HassOS 4.16
Home Assistant 0.117.6

**Comment by maykar** [comment]
Please, try pre-release version 1.4.6. If you use HACS you will need to select "Reinstall" and enable "Show beta versions"

**Comment by c0bra99** [comment]
I have installed the 1.4.6 beta version, restarted Home Assistant, and I do not see the error in my log now.

**Comment by yinonco** [comment]
works now - on 1.4.6!
