### ISSUE TITLE
Setup failed for kiosk_mode: Integration not found.

### ISSUE THREAD

**Issue by jankete** [maykar/kiosk-mode#33]
Hi, I'm using HA 0.118.3 on a VM an installed Kiosk-Mode 1.4.7 via HACS 1.6.2. The installation seemed to be successfull, as the ressource is listed unter "Configuration" > "Lovelace Dashboards" > "Resources" and the files are present on the disk in the right place.

Nevertheless the HA logs say "Setup failed for kiosk_mode: Integration not found." after I restarted my HA. And the config check says "Component error: kiosk_mode - Integration 'kiosk_mode' not found."

**Comment by KTibow** [comment]
It is not an integration to put in configuration.yaml. Read the docs again?

**Comment by jankete** [comment]
Oh man ... Seems I was blind this morning 😔 ... Closed

**Comment by KTibow** [comment]
It's okay, everyone does that now and then. Hope you do something cool with kiosk-mode!
