### ISSUE TITLE
Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by xyboox** [maykar/kiosk-mode#36]
Every ~3 out of 4 times I load the HASS UI in Chrome browser, I get the error as seen in the attached screenshot and of course the kiosk mode is not working. However, using v1.2.2 seems like the issue is not manifesting.

LE: v1.2.2 only has a slightly better loading frequency but the issue is still there.

![Screenshot at Dec 02 15-15-53](https://user-images.githubusercontent.com/642584/101016085-f6505080-3570-11eb-8494-c351291b3e18.png)

**Comment by benji1703** [comment]
Related to https://github.com/maykar/kiosk-mode/issues/23

**Comment by maykar** [comment]
Also related to https://github.com/thomasloven/hass-browser_mod/issues/163  :)

I'll see if there is anything I can do to help the issue. Stay tuned.

**Comment by browetd** [comment]
I also have errors at startup:

`2020-12-07 08:30:29 ERROR (MainThread) [frontend.js.latest.202011112] https://my DNS name:8123/hacsfiles/kiosk-mode/kiosk-mode.js:16:2 Uncaught TypeError: Cannot read property 'shadowRoot' of null
2020-12-07 08:50:14 ERROR (MainThread) [frontend.js.latest.202011112] https://my DNS name:8123/hacsfiles/kiosk-mode/kiosk-mode.js:18:15 Uncaught TypeError: Cannot read property 'config' of undefined
`

**Comment by xyboox** [comment]
Was this issue addressed, by chance, in 1.4.9? Thanks!

**Comment by maykar** [comment]
This was addressed in 1.4.9, I take it that the changes fixed it for you?

**Comment by pro469** [comment]
Good afternoon. On version 1.4.9 I get this error, how can I fix it?
http://192.168.1.117:8123/frontend_latest/core.87e3602e.js:1:7463 Uncaught Error: Suspend promise not set
http://192.168.1.117:8123/local/community/kiosk-mode/kiosk-mode.js:18:15 Uncaught TypeError: Cannot read property 'config' of undefined

**Comment by maykar** [comment]
Update to the latest version 1.5.1 and be sure to clear cache on all devices to be safe.

**Comment by pro469** [comment]
Thank you, the error does not appear.

**Comment by andrewjswan** [comment]
I clear cache and hard reload page, http://ip:8123/lovelace-wall/default_view?kiosk 
But have error:
kiosk-mode.js:21 Uncaught TypeError: Cannot read property 'admin_settings' of undefined
    at x (kiosk-mode.js:21)
    at kiosk-mode.js:35
Kiosk 1.5.1

**Comment by maykar** [comment]
Please don't post unrelated issues in the comments of a different issue and try version 1.5.2 (clear cache, etc. etc.)

**Comment by maykar** [comment]
Going to close this one, if you're still having issues, please make a new one
