### ISSUE TITLE
Hide help menu from top bar

### ISSUE THREAD

**Issue by SamMousa** [maykar/kiosk-mode#38]
When a lovelace dashboard has 2 tabs that you want to be able to access you can currently hide just the sidebar.

This is nice but leaves the help / menu in the top right visible, it would be nice if there was an option to hide this as well.
Note that when in kiosk mode it almost never makes sense to show this, so one could argue that this should always be hidden if the sidebar is hidden.

**Comment by Maximus97** [comment]
+1

**Comment by KTibow** [comment]
If you want, I think you could use card-mod themes for this.

**Comment by maykar** [comment]
As KTibow mentions this is possible with card-mod and this feels unrelated to kiosk-mode.

**Comment by SamMousa** [comment]
I disagree.. Card mod is for modding cards. Of course you can misuse it for global css but that's not what it is for.

Cardmod can also be used to hide the sidebar, the reasoning that if it can be done by another mod it shouldn't be in this one is faulty.

This is about kiosk mode, in kiosk mode you want to limit certain interactions by hiding elements. The sidebar is one of them, as is the help button..

**Comment by maykar** [comment]
I want to avoid the mistakes that were made with Custom Header, I don't want this to become another feature bloated monstrosity. If I add the ability to hide elements beyond the sidebar and header this is no longer about kiosk mode (hiding header and sidebar for real estate) and will continue to receive feature requests to hide other elements as well, then that will lead to conditional hiding of elements, and before you know it I'm making Custom Header again. 

Also, if something can already be done simply with another mod, it's still a good idea to avoid feature overlap between projects. I will consider this, but for the reasons mentioned above, I will avoid doing anything similar in the future.

**Comment by maykar** [comment]
Card mod theme to hide the overflow menu

```
  card-mod-root-yaml: |
      ha-button-menu {
        display: none;
      }
```
