### ISSUE TITLE
ERROR: TypeError: undefined is not an object (evaluating 'e.lovelace.config')

### ISSUE THREAD

**Issue by drjjr2** [maykar/kiosk-mode#39]
Logfile has several instances of:
`2020-12-20 12:55:18 ERROR (MainThread) [frontend.js.latest.202012120] https:/*****.ui.nabu.casa/hacsfiles/kiosk-mode/kiosk-mode.js:18:14 TypeError: undefined is not an object (evaluating 'e.lovelace.config')`

kiosk_mode version 1.4.7
Home Assistant version 2020.12.01

**Comment by KTibow** [comment]
What's the content of `kiosk-mode.js` line 18?

**Comment by drjjr2** [comment]
`e&&e.lovelace.config.kiosk_mode?e.lovelace.config.kiosk_mode:{}}function b(e){var r=window.location.search;return e.some(function(e){`

**Comment by drjjr2** [comment]
I don't always get these errors. In fact, I restarted the server about a day ago and I can't find any instances of this error in home-assistant.log

**Comment by KTibow** [comment]
It could be kiosk-mode loaded before lovelace.

**Comment by gigz** [comment]
seems like applying a bit more defensive programming helps to get rid of this error: e && e.lovelace && e.lovelace.config && e.lovelace.config.kiosk_mode ? e.lovelace.config.kiosk_mode : {}

I haven't found any negative side effects of this fix yet
