### ISSUE TITLE
Version 1.4.9 prevents android app from showing frontend

### ISSUE THREAD

**Issue by mrmultifunk** [maykar/kiosk-mode#42]
Hello, 
It seems that kiosk-mode is preventing the android app from showing the frontend. The issue is only there in version 1.4.9, and everything works as intended when disabling the module in HA resources. 

 I'm new to this, so any guidance with troubleshooting is appreciated.

**Comment by RomRider** [comment]
This line
https://github.com/maykar/kiosk-mode/blob/master/kiosk-mode.js#L65

fires up thousand or even millions of setTimeout() before the value can actually get to > 20, this is why it's not working.

**Comment by maykar** [comment]
Placing the `getConfig()` function in `catch` won't actually wait for config to be found, which is why I used the condition of if no config to escape the while. 

`while (llAttempts < 20 && !config) setTimeout(() => getConfig, 50);`

Also, each getConfig call increases `llAttempts` so it would only run 20 times for a total of one second. Am I missing something? Care to elaberate?

**Comment by maykar** [comment]
See the error now, fix incoming. Thanks, Rom

**Comment by maykar** [comment]
Please, update to the latest version 1.5.1 and be sure to clear cache on all devices to be safe. Report back if this solves or if you're still having issues, thank you.

**Comment by mrmultifunk** [comment]
Thanks for the quick update. However, after updating, re-enabling and clearing cache I have the same issues as before.

**Comment by maykar** [comment]
Did you install with HACS or manually? If you installed manually did you update the version number in resources as explained in the readme?

**Comment by mrmultifunk** [comment]
I have it installed with HACS. Is there anything i can do to help?

**Comment by maykar** [comment]
Is this only an issue on your android device?
If you visit on a computer and hit F12 for your dev tools console does it display the correct kiosk mode version number?

Did you follow these steps to clear the android apps cache:
* click and hold app icon
* select app info
* hit force stop
* click storage and cache
* click clear cache
* reopen app

**Comment by RomRider** [comment]
I've just issued a PR that should fix the issue @maykar : #44 ;)

**Comment by mrmultifunk** [comment]
After upgrading to 1.5.3 everything seems to be fine again. Thank you very much for you guys hard work, it is much appreciated ;)
