### ISSUE TITLE
Version 1.51 It doesn't work

### ISSUE THREAD

**Issue by wtr74** [maykar/kiosk-mode#43]
I've updated version 1.51 but it doesn't work. 
I also cancelled the cache as described. 
Back to 1.49 and everything came back perfect.
Sorry for my English
Walter

**Comment by maykar** [comment]
Issues that just say "doesn't work" aren't helpful. Provide as much info as you can, errors in logs and in your browsers dev tools (F12) are a good place to start. Try the latest version as well 1.5.2 and be sure to clear cache.

Closing for lack of info
