### ISSUE TITLE
iOS - Disable rubberband scrolling in kiosk mode

### ISSUE THREAD

**Issue by nanosonde** [maykar/kiosk-mode#45]
Hi!

I use an iPad in wallmount mode using this JS module.

However, even if all cards fit on the screen, the browser still shows this rubberband effect if you pull down the page.

I have found this snippet to disable it:
https://gist.github.com/amolk/1599412

Would it be possible to integrate this as well?

**Comment by KTibow** [comment]
Ideally that snippet wouldn't use JQuery.

**Comment by maykar** [comment]
After reading through all the comments on that gist it seems there are many unwanted side effects to incorporating something like this. Though, towards the end of the comments there is mention of simple CSS added to the body of the page to prevent the rubber band effect, but I would need to make sure that it won't effect normal scrolling within HA's cards, views, etc.

**Comment by maykar** [comment]
The CSS option causes way too many issues as well. Closing as it seems doing this would negatively affect the HA UI.

**Comment by nanosonde** [comment]
Ok, thanks anyway for considerung and testing.
