### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by franfos** [maykar/kiosk-mode#46]
Hi,
since v1.5.6 (I haven't updated a few versions ago), I get this error in logs:

> hacsfiles/kiosk-mode/kiosk-mode.js:36:23 Uncaught TypeError: Cannot read property 'length' of undefined 

I tried to install a previous version (v1.5.2 it's the oldest HACS allows me to install) but the error still it's there.

Thanks.

**Comment by SmarterHomeLife** [comment]
Hi @franfos I had similar the same issue and my HA became really sluggish, I uninstalled kiosk-mode then reinstalled 1.5.5 and everything is back to normal now.  Hope this helps.

**Comment by franfos** [comment]
> Hi @franfos I had similar the same issue and my HA became really sluggish, I uninstalled kiosk-mode then reinstalled 1.5.5 and everything is back to normal now. Hope this helps.

Yes, it worked. I've previously tried installing older versions without uninstalling the current one.

Thanks!

**Comment by etcg** [comment]
Same for me. 1.5.6 killed my home assistant instance (same error as above). CPU Usage was above 20% (3-5% before the update) all the time and it became totally unresponsive. @SmarterHomeLife Your solution worked for me! Thank you.

**Comment by jonare77** [comment]
Same here, error is thrown every second. Have 300000 occurences. Will try remove/add.

I have been step upgradring every version.

**Comment by jonare77** [comment]
1.5.5 is working as expected. Thanks @SmarterHomeLife

**Comment by maykar** [comment]
Sorry for that folks, should be good in latest.

**Comment by jonare77** [comment]
> Sorry for that folks, should be good in latest.

No problem at all. Thanks for your work!

**Comment by lolouk44** [comment]
@maykar I'm afraid I have the same issue with 1.5.8

**Comment by KTibow** [comment]
@lolouk44 clear cache? refresh?

**Comment by lolouk44** [comment]
@KTibow thanks that was it indeed. Reloaded resources and force refreshed my browser, all good now 👍
