### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by mlittle408** [maykar/kiosk-mode#51]
I am sorry for posting this here but I don't know where else to ask it. I installed kiosk-mode through HACS and it looks like it's working (I tested with the ?kiosk). I have absolutely no idea which configuration file I am supposed to edit. Where that file is and if that means I have to configure Lovelace with YAML only. I am fairly new to Home Assistant so I don't have very much experience with Lovelace. 

These two directives are where I'm stuck:

> Config is placed in the root of your Lovelace config: kiosk_mode: should not be indented & is per dashboard.
> If you want the same settings on other dashboards you'll need to repeat the config on those dashboards as well.

Is there more documentation that explains these in more detail? I've already spent an hour or so trying to find the answer myself but have had no success. 

I appreciate the help!

**Comment by maykar** [comment]
- Click `Overview` in your sidebar.
- Click the three dots menu (top-right) and click on `Edit Dashboard`.
- Click the three dots menu again and click on `Raw configuration editor`.
- There you see the configuration for your current Lovelace UI

**Comment by mlittle408** [comment]
Thank you so much! Works great and I really appreciate the quick response!!!
