### ISSUE TITLE
Will guest users be able to bypass the "kiosk_mode" using Chrome inspect tools(F12) or anything similar? 

### ISSUE THREAD

**Issue by stbeep1** [maykar/kiosk-mode#52]
I put this in the RAW configuration
kiosk_mode:
  user_settings:
    - users:
        - "guest"
        - "guest01demo"
      hide_sidebar: true

My question is will guest users be able to bypass the "kiosk_mode" using Chrome inspect tools(F12) or anything similar?

**Comment by maykar** [comment]
Yes, this is just adding css to the page
