### ISSUE TITLE
Component error: resources - Integration 'resources' not found.

### ISSUE THREAD

**Issue by Konofat** [maykar/kiosk-mode#54]
Hi!

I `m new to home assistant and just making my first steps. I tried to install kiosk-mode with HACS but i can`t make it work. I repeated all the steps over and over agian 

1. Install using HACS

2. edit configuration.yaml

What am I missing?

**Comment by KTibow** [comment]
First of all, you're pressing the backtick button instead of a single quote button.
Have you tried reloading?
What did you put in `configuration.yaml`?

**Comment by maykar** [comment]
The installation portion of the readme explains where to add the resources section depending on if you are using Storage mode (the default mode) or YAML mode. If you're unsure which mode you use, you are most likely using storage mode and wouldn't add anything into configuration.yaml. You can find where to add resources in the installation instructions. If you use YAML mode there is a link in the installation instructions showing how and where to put resources in configuration.yaml.

To add configuration for kiosk mode:

* If you use storage mode: click the top right menu button on a lovelace page, select "edit dashboard", click that top right button again and select "raw config editor"

* If you use YAML mode, configuration for kiosk-mode goes in your ui-lovelace.yaml
