### ISSUE TITLE
Uncaught Reference Error

### ISSUE THREAD

**Issue by liamstears** [maykar/kiosk-mode#55]
I seem to have something going wrong, pressing f12 in Chrome gives me the following:

`Uncaught (in promise) ReferenceError: regeneratorRuntime is not defined
    at v (kiosk-mode.js:37)
    at k (kiosk-mode.js:37)
    at kiosk-mode.js:44`

Please let me know what info you need to diagnose and I will send it, this is on latest HomeAssistant build (I keep everything up to date)

**Comment by KTibow** [comment]
It's a problem with the build process (google "regeneratorRuntime is not defined babel"). As a temp fix, use the [raw JS](https://raw.githubusercontent.com/maykar/kiosk-mode/master/kiosk-mode.js) instead. I'm not sure what the best way to do this in CI is; I think I would need to create a temporary file.

**Comment by liamstears** [comment]
> It's a problem with the build process (google "regeneratorRuntime is not defined babel"). As a temp fix, use the [raw JS](https://raw.githubusercontent.com/maykar/kiosk-mode/master/kiosk-mode.js) instead. I'm not sure what the best way to do this in CI is; I think I would need to create a temporary file.

Using the raw JS has fixed it for now but I would much prefer to use HACS

Can you not get HACS to use the raw JS?

I'm no dev so not sure how the build process works for a plugin like this...

**Comment by maykar** [comment]
Installing the version called "Master" in HACS is the same as using the raw JS.

**Comment by xyboox** [comment]
Using master in HACS is still generating that error.

**Comment by maykar** [comment]
If you're receiving the same error on the master branch then you need to clear the cache of all the devices accessing HA. The master branch cannot create this error.

**Comment by maykar** [comment]
This should be solved in the latest releases, no need for using master branch
