### ISSUE TITLE
Add swipe to change tabs

### ISSUE THREAD

**Issue by krestes** [maykar/kiosk-mode#56]
Can you add a swipe to move between tabs when the header is hidden.

**Comment by olivierboudet** [comment]
I agree it would be very useful. I have tabs on my lovelace view but I can't switch from one to others if I hide the header.

**Comment by maykar** [comment]
I assume you are referring to my other project [Swipe-Navigation](https://github.com/maykar/lovelace-swipe-navigation). Are you not able to use it's config option of `skip_hidden: false` to achieve what you're looking for?

**Comment by krestes** [comment]
You are right I posted this before I found Swipe-Navigation that app is able to do what I needed, Thanks for the response. Sent from Mail for Windows 10 From: Ryan MeekSent: Sunday, February 7, 2021 11:13 AMTo: maykar/kiosk-modeCc: krestes; AuthorSubject: Re: [maykar/kiosk-mode] Add swipe to change tabs (#56) I assume you are referring to my other project Swipe-Navigation. Are you not able to use it's config option of skip_hidden: false to achieve what you're looking for?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
