### ISSUE TITLE
Flag to hide the "Do you want to stay logged in" prompt

### ISSUE THREAD

**Issue by Schonhoffer** [maykar/kiosk-mode#59]
I'm using "Trusted networks" to allow my TV via cast to show the dashboard, but I can't dismiss the "Do you want to stay logged in" prompt in the bottom right-hand corner.

Would you accept a PR to add a feature to hide that as well?

**Comment by KTibow** [comment]
From what I remember, @maykar doesn't want this to get super complicated like custom-header.

**Comment by maykar** [comment]
This would be better fit in a different project, though if you find the button's element I know you could do this with card-mod
