### ISSUE TITLE
Add kiosk_mode under json

### ISSUE THREAD

**Issue by abeksis** [maykar/kiosk-mode#62]
Thanks for this special plugin.

I build the interface through the homeassisteint ui. Is there a way to add kiosk mode?

**Comment by maykar** [comment]
Click the top right three dots in Lovelace and select "Edit Dashboard", then click that top right menu again and select "Raw configuration editor" to add your config for kiosk-mode.

**Comment by abeksis** [comment]
thank you for the answer.
I did what you said, but it does not work.
before:

`views:
  - theme: dmatik-light
    title: Home
    path: ipadhonm
    panel: false
    visible:
      - user: a6b098a5910c46d58c4f1d0ccf183306
      - user: c710d585c9ae4c4a9da525556535ddea
      - user: 03b68397290c4fbfa15f00df4972136f
      - user: 2349b22e7bbc43148284757c5246b1ad
      - user: 570b1f9914ae4e4894b585e816d666f8
      - user: dff9bc9930314c72ab89d6ec586fa3be
    badges: []`

after:

`kiosk_mode:
  hide_header: true
views:
  - theme: dmatik-light
    title: Home
    path: ipadhonm
    panel: false
    visible:
      - user: a6b098a5910c46d58c4f1d0ccf183306
      - user: c710d585c9ae4c4a9da525556535ddea
      - user: 03b68397290c4fbfa15f00df4972136f
      - user: 2349b22e7bbc43148284757c5246b1ad
      - user: 570b1f9914ae4e4894b585e816d666f8
      - user: dff9bc9930314c72ab89d6ec586fa3be
    badges: []
    cards:`

what am I missing

**Comment by maykar** [comment]
How did you install kiosk_mode? Does it show up in your brower's dev tools (F12) and are there any errors listed there for kiosk_mode?

**Comment by abeksis** [comment]
I installed via hack - regarding errors, I check and repeat.

**Comment by abeksis** [comment]
https://imgur.com/OSQXssB

**Comment by maykar** [comment]
So yeah, it's not loaded. Try a cache clear/reload (`shift+ctrl+R` should do it on most systems).

**Comment by abeksis** [comment]
https://imgur.com/WWvRDkm

**Comment by maykar** [comment]
* Try reinstalling with HACS
* Make sure `www/community/kiosk-mode` exists
* Make sure the resource was created in `Configuration > Lovelace Dashboards > Resources`

`/hacsfiles/kiosk-mode/kiosk-mode.js`

**Comment by abeksis** [comment]
Thank you. Everything works.
